# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

if ENV['batch']
    username "croing09@gmail.com"
    app_identifier "com.stells.batch"
    metadata_path "./fastlane/com.stells.batch"
    screenshots_path "/Users/blackgene/Documents/pap\-resources/appstore/screenshots/batch"
    ipa "batch.ipa"
elsif ENV['mmc']
    username "illhert@yahoo.com"
    app_identifier "com.stells.mmc"
    metadata_path "./fastlane/com.stells.mmc"
    screenshots_path "/Users/blackgene/Documents/pap\-resources/appstore/screenshots/mmc"
    ipa "mmc.ipa"
end
